version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgresdb1
    environment:
      POSTGRES_DB: controlefinanceiro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
volumes:
  postgres_data:
